stages:
  - maven-build
  - docker-build
  
maven-build:
  image: maven
  stage: maven-build
  script: mvn install
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker logout
  dependencies:
    - maven-build